DVD_FILES := \
$(ASSETS)/rels/$(TARGET)_P1.rel.LZ \
$(ASSETS)/rels/$(TARGET)_P2.rel.LZ \
$(ASSETS)/rels/$(TARGET)_E1.rel.LZ \
$(ASSETS)/rels/$(TARGET)_E2.rel.LZ \
$(ASSETS)/rels/$(TARGET)_J1.rel.LZ \
$(ASSETS)/rels/$(TARGET)_J2.rel.LZ \
$(ASSETS)/rels/$(TARGET)_K1.rel.LZ \
$(ASSETS)/rels/$(TARGET)_W1.rel.LZ \
$(ASSETS)/rels/$(TARGET)_C1.rel.LZ \
$(ASSETS)/rels/project.SMAP \
$(ASSETS)/Layout/charaChangeSelectContents/charaChangeSelectContents.arc/arc/blyt/characterChangeSelectContents_05.brlyt \
$(ASSETS)/Layout/charaChangeSelectContents/charaChangeSelectContents.arc/arc/timg/Im_plofileMario_00.tpl \
$(ASSETS)/Layout/corseSelectUIGuide/corseSelectUIGuide.arc/arc/blyt/corseSelectUIGuide_37.brlyt \
$(ASSETS)/Layout/corseSelectUIGuide/corseSelectUIGuide.arc/arc/timg/im_kinopicoIcon_01.tpl \
$(ASSETS)/Layout/corseSelectUIGuide/corseSelectUIGuide.arc/arc/timg/im_kinopicoIcon_Purple_01.tpl \
$(ASSETS)/Layout/corseSelectUIGuide/corseSelectUIGuide.arc/arc/timg/im_kinopioIcon_Black_01.tpl \
$(ASSETS)/Layout/corseSelectUIGuide/corseSelectUIGuide.arc/arc/timg/im_kinopioIcon_Orange_01.tpl \
$(ASSETS)/Layout/fileSelectPlayer/fileSelectPlayer.arc/arc/blyt/fileSelectPlayer_23.brlyt \
$(ASSETS)/Layout/fileSelectPlayer/fileSelectPlayer.arc/arc/anim/fileSelectPlayer_23_offPlayerButton.brlan \
$(ASSETS)/Layout/fileSelectPlayer/fileSelectPlayer.arc/arc/anim/fileSelectPlayer_23_onPlayerButton.brlan \
$(ASSETS)/Layout/fileSelectPlayer/fileSelectPlayer.arc/arc/anim/fileSelectPlayer_23_hitPlayerButton.brlan \
$(ASSETS)/Layout/gameScene/gameScene.arc/arc/blyt/gameScene_37.brlyt \
$(ASSETS)/Layout/gameScene/gameScene.arc/arc/timg/im_kinopicoIcon_01.tpl \
$(ASSETS)/Layout/gameScene/gameScene.arc/arc/timg/im_kinopicoIcon_Purple_01.tpl \
$(ASSETS)/Layout/gameScene/gameScene.arc/arc/timg/im_kinopioIcon_Black_01.tpl \
$(ASSETS)/Layout/gameScene/gameScene.arc/arc/timg/im_kinopioIcon_Orange_01.tpl \
$(ASSETS)/Layout/miniGameWire/miniGameWire.arc/arc/blyt/miniGameWire_12.brlyt \
$(ASSETS)/Layout/miniGameWire/miniGameWire.arc/arc/timg/im_kinopicoIcon_01.tpl \
$(ASSETS)/Layout/miniGameWire/miniGameWire.arc/arc/timg/im_kinopicoIcon_Purple_01.tpl \
$(ASSETS)/Layout/miniGameWire/miniGameWire.arc/arc/timg/im_kinopioIcon_Black_01.tpl \
$(ASSETS)/Layout/miniGameWire/miniGameWire.arc/arc/timg/im_kinopioIcon_Orange_01.tpl \
$(ASSETS)/Layout/preGame/preGame.arc/arc/blyt/preGame_19.brlyt \
$(ASSETS)/Layout/preGame/preGame.arc/arc/timg/im_kinopicoIcon_01.tpl \
$(ASSETS)/Layout/preGame/preGame.arc/arc/timg/im_kinopicoIcon_Purple_01.tpl \
$(ASSETS)/Layout/preGame/preGame.arc/arc/timg/im_kinopioIcon_Black_01.tpl \
$(ASSETS)/Layout/preGame/preGame.arc/arc/timg/im_kinopioIcon_Orange_01.tpl \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/anim/staffCredit_00_inHighScore.brlan \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/anim/staffCredit_00_inPlayerScore.brlan \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/anim/staffCredit_00_loopPlayerScore.brlan \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/anim/staffCredit_00_newHighScore.brlan \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/anim/staffCredit_00_winPlayer.brlan \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/blyt/staffCredit_00.brlyt \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/timg/im_kinopicoIcon_01.tpl \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/timg/im_kinopicoIcon_gray.tpl \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/timg/im_kinopicoIcon_Purple_01.tpl \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/timg/im_kinopicoIcon_Purple_gray.tpl \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/timg/im_kinopioIcon_Black_01.tpl \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/timg/im_kinopioIcon_Black_gray.tpl \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/timg/im_kinopioIcon_Orange_01.tpl \
$(ASSETS)/Layout/staffCredit/staffCredit.arc/arc/timg/im_kinopioIcon_Orange_gray.tpl \
$(ASSETS)/Object/C_rcha.arc/g3d/model.brres \
$(ASSETS)/Object/Kinopico.arc/g3d/model.brres \
$(ASSETS)/Object/KinopicoPurple.arc/g3d/model.brres \
$(ASSETS)/Object/KinopioBlackOrange.arc/g3d/model.brres \
$(ASSETS)/Object/MG_remo_cannon.arc/g3d/MG_remo_cannon.brres \
$(ASSETS)/Object/middle_flag.arc/g3d/middle_flag.brres \
$(ASSETS)/Object/remo_kanaami.arc/g3d/remo_kanaami.brres \
$(ASSETS)/Object/remo_lift_line.arc/g3d/remo_lift_line.brres \
$(ASSETS)/Object/remo_lift_soroban.arc/g3d/remo_lift_soroban.brres \
$(ASSETS)/Object/remo_lift_up.arc/g3d/remo_lift_up.brres \
$(ASSETS)/Object/remo_lift.arc/g3d/remo_lift.brres \
$(ASSETS)/Sound/BANK_SE_VOC_COURSE_KC.brbnk \
$(ASSETS)/Sound/GROUP_SE_VOC_COURSE_KC.brwar \
$(ASSETS)/Stage/01-09.arc.LZ
